services:
  db:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build: ./backend
    restart: always
    platform: linux/amd64
    environment:
      - DEBUG=True
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  mysql_data:
