# Generated by Django 4.2.7 on 2026-02-03 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='龙猫图书管理系统', max_length=50, verbose_name='系统名称')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='维护模式')),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.RemoveField(
            model_name='loanrecord',
            name='remark',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='总库存'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='归还日期'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('borrowed', '借阅中'), ('returned', '已归还'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借阅人'),
        ),
    ]
