# Generated by Django 4.2.7

from django.db import migrations, models


def set_empty_isbn_to_null(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Book.objects.filter(isbn='').update(isbn=None)


def set_null_isbn_to_empty(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Book.objects.filter(isbn__isnull=True).update(isbn='')


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_preview_file'),
    ]

    operations = [
        migrations.RunPython(set_empty_isbn_to_null, set_null_isbn_to_empty),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
