# Generated by Django 4.2.7 on 2026-06-05 22:58

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_preview_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='book_previews/', validators=[apps.books.models.validate_pdf_file], verbose_name='试读章节 (PDF)'),
        ),
    ]
