# Generated by Django 4.2.7 on 2026-06-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('borrowed', '借阅中'), ('returned', '已归还'), ('rejected', '已拒绝'), ('damaged', '待赔偿')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
